import Foundation

enum ClipPrivacy {
    // Publicly used pasteboard conventions, not private API calls. Not every source app supplies them.
    static func isPrivate(types: [String]) -> Bool {
        types.contains { type in
            let value = type.lowercased()
            return [
                "concealed", "transient", "password", "sensitive", "org.nspasteboard.autogenerated",
                "de.thamo.clipity.clipping",
            ].contains { value.contains($0) }
        }
    }

    static func looksSensitive(_ text: String) -> Bool {
        let value = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let patterns = [
            #"(?i)-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"#,
            #"(?i)(?:password|passwd|api[_ -]?key|secret|access[_ -]?token)\s*[:=]\s*\S+"#,
            #"(?i)\b(?:sk-[A-Za-z0-9_-]{16,}|gh[pousr]_[A-Za-z0-9]{20,}|AKIA[A-Z0-9]{16})\b"#,
            #"^\d{4,8}$"#,
            #"^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$"#,
        ]
        if patterns.contains(where: { value.range(of: $0, options: .regularExpression) != nil }) { return true }
        if let components = URLComponents(string: value), components.scheme != nil {
            if components.user != nil || components.password != nil { return true }
            if components.queryItems?.contains(where: { item in
                ["token", "key", "secret", "password", "code", "signature"].contains {
                    item.name.lowercased().contains($0)
                }
            }) == true {
                return true
            }
        }
        let digits = value.filter(\.isNumber)
        if (13...19).contains(digits.count), value.allSatisfy({ $0.isNumber || $0 == " " || $0 == "-" }) {
            let sum = digits.reversed().enumerated().reduce(0) { sum, item in
                let number = item.element.wholeNumberValue ?? 0
                let doubled = item.offset.isMultiple(of: 2) ? number : number * 2
                return sum + (doubled > 9 ? doubled - 9 : doubled)
            }
            if sum.isMultiple(of: 10) { return true }
        }
        // Conservatively skip compact, password-like mixed strings. This is a heuristic, not a guarantee.
        return value.count >= 8 && value.count <= 128 && !value.contains(where: \.isWhitespace)
            && value.rangeOfCharacter(from: .uppercaseLetters) != nil
            && value.rangeOfCharacter(from: .lowercaseLetters) != nil
            && value.rangeOfCharacter(from: .decimalDigits) != nil
            && URL(string: value)?.scheme == nil
    }
}
